### ATUALIZAR PRODUTO
DELETE http://localhost:3000/produtos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NjQwMTU1NTQsImV4cCI6MTc2NDA0NDM1NH0.l9nHFYse-O2Pdp8mVJHkN6jehDyM8zur2ylAKdyRJos
